/*
**/


/**/
class GBaseLayer extends GLayer
{
	/**/
	function GBaseLayer(window, parent, handler)
	{
		super.GLayer(...);

		hitThreshold = 0;
		type = ltOpaque;
		neutralColor = 0x000000;
	}

	function clearImages()
	{
		super.clearImages(0xFF000000);
	}

	/**/
	function assign(src)
	{
		// NOTE: •\¦ó‘Ô‚¾‚¯‚Í“¯Šú‚³‚¹‚È‚¢B
		var backup = visible;

		super.assign(src);

		visible = backup;
	}

	/**/
	function onMouseUp(x, y, button, shift)
	{
		switch(button)
		{
		case mbLeft:	window.leftClick(x, y, shift); break;
		case mbRight:	window.rightClick(x, y, shift); break;
		case mbMiddle:	window.middleClick(x, y, shift); break;
		}
	}
}


